### ISSUE TITLE
放在自定义规则集不生效

### ISSUE THREAD

**Issue by brucmao** [wgetnz/chatgpt-openclash#2]
openclash 已经启用 meta 内核
![image](https://user-images.githubusercontent.com/6119652/223800674-4f6b7be2-9569-4e80-b1ea-efc6a05ea975.png)

![image](https://user-images.githubusercontent.com/6119652/223800381-5814d919-3117-4bc3-9dd6-3a6342be85f6.png)

**Comment by wgetnz** [comment]
这个是失效的

**Comment by brucmao** [comment]
我看了下，自定义规则集应该是yaml格式才行

**Comment by wgetnz** [comment]
> 我看了下，自定义规则集应该是yaml格式才行

之前想这么弄，后面想了下，没继续支持了

**Comment by brucmao** [comment]
**重要**
```diff
- openclash 启用 meta 内核
- openclash 需要打开 udp  才行（被这个坑了很久）https://www.v2ex.com/t/900491#r_12708197
```

最后，我是在**全局设置->规则设置-自定义规则（优先匹配）**
`- DOMAIN-SUFFIX,openai.com,🧠 chatgpt`
然后在 **服务器与策略组管理->策略组配置**  配置需要的节点
![image](https://user-images.githubusercontent.com/6119652/223894375-4992a3ff-0555-40ab-ba62-be15fa0fa247.png)

对应配置文件为
```
- name: "\U0001F9E0 chatgpt"
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  proxies:
  - "\U0001F1FA\U0001F1F8 美国 \U0001F13C"
  - "\U0001F1FA\U0001F1F8 美国 \U0001F144"
  - "\U0001F1FA\U0001F1F8 美国 \U0001F132"
  url: http://www.gstatic.com/generate_204
  interval: '300'
  filter: us|美国
```
